### ISSUE TITLE
publish workflow: --publish-only flag is a silent no-op (Telegram final report never sends)

### ISSUE THREAD

**Issue by neverbiasu** [ai-newsday/core#6]
## Problem
`.github/workflows/publish.yml` runs:

```yaml
- name: Send Telegram final report
  run: uv run python -m src.cli --tick finalize --publish-only 2>/dev/null || true
```

But `src/cli.py` does not implement a `--publish-only` flag. Combined with `2>/dev/null || true`, the step silently does nothing — so **the Telegram final report is never sent on publish**.

Functional publish (flip draft → false, commit, Pages rebuild) is unaffected; only the notification is missing.

## Fix options
1. Implement `--publish-only` in `cli.py`: a mode that re-renders the finalized report and sends only the Telegram final report (no re-collect, no re-write of content/posts).
2. Once implemented, remove the `2>/dev/null || true` guard so a real failure surfaces in CI.

## Acceptance
- Running the publish workflow sends a Telegram message with the day's final report.
- The step fails loudly if the send fails (no silent swallow).

Context: introduced in PR #5 (draft-preview-publish). The guard was intentional to avoid blocking publish before the flag existed.

**Comment by neverbiasu** [comment]
Copilot's PR #5 review surfaced a sharper version of this: even if `--publish-only` is implemented by reusing the existing `finalize` tick, that tick's `WebsiteNotifier` calls `publish()`, which **always emits `draft: true`** — so it would rewrite `content/posts/<date>.md` and **undo the `flip_draft` step that just ran**.

So the publish path needs more than a flag — it must either:
- send Telegram **without** re-rendering / re-writing the post file, or
- render with `draft: false` when in publish mode.

Acceptance updated: publishing must send the Telegram final report **and** leave the already-flipped `draft: false` post intact.
